### ISSUE TITLE
Wrong output maybe for Question 5

### ISSUE THREAD

**Issue by rajmanikush** [shobhakartiwari/iOS_Lead_Interview#2]
I see the expected answer is written as 

```
Will set to 1
Did set from 2 to 1
Will set to 3
Did set from 1 to 3
```

However, property observers get triggered only after the self-scope and do not get triggered during the initialisation. I tried validating it with Playground and got the output only after the object was created.

<img width="735" alt="Screenshot 2024-11-10 at 5 38 29 PM" src="https://github.com/user-attachments/assets/4424bd65-8f11-4ffd-9427-d73588fda544">

Can you please validate it?

**Comment by shobhakartiwari** [comment]
@rajmanikush thanks for the feedback , yes its mistake , you are right. corrected and pushed new changes.
